# Generated by Django 4.1.3 on 2022-12-13 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nosh_app", "0002_recipe_description_recipe_quantity_recipe_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cookbook",
            name="recipes",
            field=models.ManyToManyField(
                through="nosh_app.CookbookRecipe", to="nosh_app.recipe"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="section",
            name="recipes",
            field=models.ManyToManyField(
                through="nosh_app.CookbookRecipe", to="nosh_app.recipe"
            ),
        ),
        migrations.AlterField(
            model_name="cookbookrecipe",
            name="cookbook",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="nosh_app.cookbook",
            ),
        ),
    ]
